services:
  kavita:
    image: jvmilazz0/kavita:0.9.1
    environment:
      TZ: ${TZ}
    ports:
      - 5000
    volumes:
      - kavita-config:/kavita/config
      - books:/books
      - comics:/comics
      - manga:/manga
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
volumes:
  books:
    driver_opts:
      size: 1.5Gi
  manga:
    driver_opts:
      size: 1.5Gi
  comics:
    driver_opts:
      size: 1.5Gi
  kavita-config:
    driver_opts:
      size: 256Mi
