services:
  clickhouse:
    image: clickhouse/clickhouse-server:26.9.10.4
    environment:
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
    ports:
      - 8123
      - 9000
    volumes:
      - data:/var/lib/clickhouse
    deploy:
      resources:
        reservations:
          cpus: 0.5
          memory: 1G
volumes:
  data:
    driver_opts:
      size: 2Gi
