services:
  litellm:
    image: ghcr.io/berriai/litellm:v1.104.0
    environment:
      DATABASE_URL: postgresql://litellm:${POSTGRES_PASSWORD}@db:5432/litellm
      STORE_MODEL_IN_DB: "True"
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY}
      LITELLM_SALT_KEY: ${LITELLM_SALT_KEY}
      UI_USERNAME: ${UI_USERNAME}
      UI_PASSWORD: ${UI_PASSWORD}
    ports:
      - 4000
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          cpus: 0.5
          memory: 2G
  db:
    image: postgres:18.6
    environment:
      POSTGRES_DB: litellm
      POSTGRES_USER: litellm
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-U", "litellm", "-d", "litellm"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 60s
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
volumes:
  db:
    driver_opts:
      size: 2Gi
