services:
  mailpit:
    image: axllent/mailpit:v1.31.4
    environment:
      MP_DATABASE: /data/mailpit.db
      MP_MAX_MESSAGES: "5000"
      MP_SMTP_AUTH_ACCEPT_ANY: "1"
      MP_SMTP_AUTH_ALLOW_INSECURE: "1"
      MP_UI_AUTH: ${MP_UI_AUTH}
    ports:
      - 8025
      - 1025
    volumes:
      - data:/data
    deploy:
      resources:
        reservations:
          cpus: 0.1
          memory: 128M
volumes:
  data:
    driver_opts:
      size: 1Gi
