services:
  mumble-server:
    image: mumblevoip/mumble-server:v1.5.915
    environment:
      MUMBLE_SUPERUSER_PASSWORD: ${MUMBLE_SUPERUSER_PASSWORD}
      MUMBLE_CONFIG_SERVER_PASSWORD: ${SERVER_PASSWORD}
    ports:
      - 64738/tcp
      - 64738/udp
    volumes:
      - data:/data
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 128M
volumes:
  data:
    driver_opts:
      size: 512Mi
