services:
  phpmyadmin:
    image: phpmyadmin:5.2.3
    environment:
      PMA_ARBITRARY: "1"
    ports:
      - 80
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
