services:
  headscale:
    image: headscale/headscale:0.29.4-debug
    command: serve
    environment:
      HEADSCALE_SERVER_URL: ${PUBLIC_URL}
      HEADSCALE_DNS_BASE_DOMAIN: ${BASE_DOMAIN}
    configs:
      - source: config.yaml
        target: /etc/headscale/config.yaml
    ports:
      - 8080
    volumes:
      - data:/var/lib/headscale
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
volumes:
  data:
    driver_opts:
      size: 512Mi
configs:
  config.yaml:
    file: ./configs/config.yaml
