services:
  crafty:
    image: registry.gitlab.com/crafty-controller/crafty-4:4.11.0
    environment:
      TZ: ${TZ}
    ports:
      - 8443
      - 8123
      - 19132/udp
    volumes:
      - backups:/crafty/backups
      - logs:/crafty/logs
      - servers:/crafty/servers
      - config:/crafty/app/config
      - import:/crafty/import
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
volumes:
  logs:
    driver_opts:
      size: 256Mi
  config:
    driver_opts:
      size: 256Mi
  import:
    driver_opts:
      size: 1.5Gi
  backups:
    driver_opts:
      size: 1.5Gi
  servers:
    driver_opts:
      size: 1.5Gi
