services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:3.0.2
    environment:
      SECURITY_ENABLELOGIN: "true"
      SECURITY_INITIALLOGIN_USERNAME: ${ADMIN_USERNAME}
      SECURITY_INITIALLOGIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - 8080
    volumes:
      - config:/configs
      - tessdata:/usr/share/tessdata
    deploy:
      resources:
        reservations:
          cpus: 1
          memory: 2G
volumes:
  config:
    driver_opts:
      size: 1Gi
  tessdata:
    driver_opts:
      size: 1Gi
