services:
  librechat:
    image: ghcr.io/danny-avila/librechat:v0.8.7
    environment:
      HOST: 0.0.0.0
      MONGO_URI: mongodb://librechat:${MONGO_PASSWORD}@mongodb:27017/LibreChat?authSource=admin
      MEILI_HOST: http://meilisearch:7700
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      SEARCH: "true"
      DOMAIN_CLIENT: ${PUBLIC_URL}
      DOMAIN_SERVER: ${PUBLIC_URL}
      CREDS_KEY: ${CREDS_KEY}
      CREDS_IV: ${CREDS_IV}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      ALLOW_REGISTRATION: ${ALLOW_REGISTRATION}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      GOOGLE_KEY: ${GOOGLE_KEY}
      CONFIG_PATH: ${CONFIG_PATH}
    ports:
      - 3080
    volumes:
      - images:/app/client/public/images
      - uploads:/app/uploads
    depends_on:
      - mongodb
      - meilisearch
    deploy:
      resources:
        reservations:
          cpus: 0.5
          memory: 1G
  mongodb:
    image: mongo:8.0.32
    environment:
      MONGO_INITDB_ROOT_USERNAME: librechat
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    expose:
      - 27017
    volumes:
      - mongo-data:/data/db
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 512M
  meilisearch:
    image: getmeili/meilisearch:v1.35.1
    environment:
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    expose:
      - 7700
    volumes:
      - meili-data:/meili_data
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
volumes:
  images:
    driver_opts:
      size: 512Mi
  uploads:
    driver_opts:
      size: 2Gi
  mongo-data:
    driver_opts:
      size: 1Gi
  meili-data:
    driver_opts:
      size: 512Mi
