services:
  meilisearch:
    image: getmeili/meilisearch:v1.54.3
    environment:
      MEILI_ENV: production
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    ports:
      - 7700
    volumes:
      - data:/meili_data
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 512M
volumes:
  data:
    driver_opts:
      size: 2Gi
